# Generated by Django 3.0.2 on 2020-03-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundooappnote', '0002_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='person',
        ),
    ]