# Generated by Django 3.0.2 on 2020-03-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundooappnote', '0003_auto_20200306_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='person',
            new_name='user',
        ),
    ]
