# Generated by Django 3.0.4 on 2020-03-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooappnote', '0007_auto_20200309_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pinnote',
            field=models.BooleanField(default=False),
        ),
    ]
