# Generated by Django 3.0.4 on 2020-03-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooappnote', '0008_note_pinnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
