# Generated by Django 3.0.4 on 2020-03-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooappnote', '0009_note_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
