# Generated by Django 3.0.4 on 2020-03-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooappnote', '0010_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
