# Generated by Django 3.0.4 on 2020-03-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooappnote', '0011_note_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='time',
        ),
        migrations.AddField(
            model_name='note',
            name='remainder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
