# Generated by Django 3.0.4 on 2020-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooappnote', '0013_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='note',
            field=models.ManyToManyField(blank=True, to='fundooappnote.Note'),
        ),
    ]
