# Generated by Django 3.0.4 on 2020-03-23 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundooappnote', '0014_collaborators_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='Note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Collaborators',
        ),
    ]
